
services:
  authservice:
    build: ./AuthService
    container_name: authservice
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Key: THIS_IS_A_DEV_SECRET_CHANGE_LATER
    restart: unless-stopped

  # orderservice:
  #   build: ./OrderService
  #   container_name: orderservice
  #   ports:
  #     - "5001:8080"
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #   restart: unless-stopped

  # customerservice:
  #   build: ./CustomerService
  #   container_name: customerservice
  #   ports:
  #     - "5002:8080"
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #   restart: unless-stopped
